/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cci.mapui;

/**
 *
 * @author itsadmin
 */
public class MapDisplay extends javax.swing.JFrame {

    /**
     * Creates new form MapDisplay
     */
    public MapDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchByPanel = new javax.swing.JPanel();
        nameComboBox = new javax.swing.JComboBox();
        roomNumberComboBox = new javax.swing.JComboBox();
        roomNameComboBox = new javax.swing.JComboBox();
        searchForLabel = new javax.swing.JLabel();
        searchForTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        mapPane = new javax.swing.JTabbedPane();
        firstTab = new javax.swing.JPanel();
        firstFloorLabel = new javax.swing.JLabel();
        secondTab = new javax.swing.JPanel();
        secondFloorLabel = new javax.swing.JLabel();
        thirdTab = new javax.swing.JPanel();
        thirdFloorLabel = new javax.swing.JLabel();
        fourthTab = new javax.swing.JPanel();
        fourthFloorLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 1100));

        searchByPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search By", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        nameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Faculty or Staff Name", "Item 2", "Item 3", "Item 4" }));

        roomNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Room Number", "Item 2", "Item 3", "Item 4" }));

        roomNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lab or Center", "Item 2", "Item 3", "Item 4" }));

        searchForLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchForLabel.setText("Enter Text to Search");
        searchForLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        submitButton.setText("Submit");

        javax.swing.GroupLayout searchByPanelLayout = new javax.swing.GroupLayout(searchByPanel);
        searchByPanel.setLayout(searchByPanelLayout);
        searchByPanelLayout.setHorizontalGroup(
            searchByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchForLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameComboBox, 0, 156, Short.MAX_VALUE)
                    .addComponent(roomNumberComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchForTextField))
                .addContainerGap())
            .addGroup(searchByPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchByPanelLayout.setVerticalGroup(
            searchByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(searchForLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchForTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        mapPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mapPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        firstFloorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cci/mapui/images/1stfloor.png"))); // NOI18N

        javax.swing.GroupLayout firstTabLayout = new javax.swing.GroupLayout(firstTab);
        firstTab.setLayout(firstTabLayout);
        firstTabLayout.setHorizontalGroup(
            firstTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstFloorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        firstTabLayout.setVerticalGroup(
            firstTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstFloorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mapPane.addTab("First Floor", firstTab);

        secondFloorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cci/mapui/images/2ndfloor.png"))); // NOI18N

        javax.swing.GroupLayout secondTabLayout = new javax.swing.GroupLayout(secondTab);
        secondTab.setLayout(secondTabLayout);
        secondTabLayout.setHorizontalGroup(
            secondTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secondFloorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        secondTabLayout.setVerticalGroup(
            secondTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(secondFloorLabel)
                .addGap(271, 271, 271))
        );

        mapPane.addTab("Second Floor", secondTab);

        thirdFloorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cci/mapui/images/3rdfloor.png"))); // NOI18N

        javax.swing.GroupLayout thirdTabLayout = new javax.swing.GroupLayout(thirdTab);
        thirdTab.setLayout(thirdTabLayout);
        thirdTabLayout.setHorizontalGroup(
            thirdTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thirdFloorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thirdTabLayout.setVerticalGroup(
            thirdTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thirdFloorLabel)
                .addGap(490, 490, 490))
        );

        mapPane.addTab("Third Floor", thirdTab);

        fourthFloorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/cci/mapui/images/4thfloor.png"))); // NOI18N

        javax.swing.GroupLayout fourthTabLayout = new javax.swing.GroupLayout(fourthTab);
        fourthTab.setLayout(fourthTabLayout);
        fourthTabLayout.setHorizontalGroup(
            fourthTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourthTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fourthFloorLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        fourthTabLayout.setVerticalGroup(
            fourthTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fourthTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fourthFloorLabel)
                .addGap(462, 462, 462))
        );

        mapPane.addTab("Fourth Floor", fourthTab);

        jButton1.setText("Search Faculty By Image");

        jButton2.setText("Search Staff By Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchByPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addGap(32, 32, 32)
                .addComponent(mapPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mapPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(searchByPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstFloorLabel;
    private javax.swing.JPanel firstTab;
    private javax.swing.JLabel fourthFloorLabel;
    private javax.swing.JPanel fourthTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTabbedPane mapPane;
    private javax.swing.JComboBox nameComboBox;
    private javax.swing.JComboBox roomNameComboBox;
    private javax.swing.JComboBox roomNumberComboBox;
    private javax.swing.JPanel searchByPanel;
    private javax.swing.JLabel searchForLabel;
    private javax.swing.JTextField searchForTextField;
    private javax.swing.JLabel secondFloorLabel;
    private javax.swing.JPanel secondTab;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel thirdFloorLabel;
    private javax.swing.JPanel thirdTab;
    // End of variables declaration//GEN-END:variables
}
